### ISSUE TITLE
Sengled bulb integration

### ISSUE THREAD

**Issue by tascotim** [jfarmer08/ha-sengledapi#72]
I have downloaded the Sengled bulb integration into HACS Integrations.  It shows up there but not when I go back to integrations to add it.

**Comment by jfarmer08** [comment]
You have to add the following to your config manually. 
`sengledapi:
  username: <email for sengled>
  password: <password for sengled>
  country: <country>
  wifi: true`

**Comment by YaKillaCJ** [comment]
First off, thank you for the hardwork.
Maybe I am missing something but Im having same issue. Can you make it Dummy proof in the Readme. I have added it via HACS, restarted. Opened HA settings, Add-ons,  File editor, Open Web Ui > Browse Filesystem, custom_components, sengledapi > const.py *I assume this the correct file*. I then deleted everything. Used this exact layout and spacing:

sengledapi:
  username: c****@****.com
  password: ***password***
  country: us
  wifi: true

I assume Im supposed to remove the brackets <> and just type email and password. I used the copy button via gethub and edited in my username password. Thus its 5 lines of text and no space before line 1 and 2 spaces before the 4 bottom lines. Saved. Restarted. I get nothing under HA integration tab, nor does it come up in the list via + Add Integration. Understand Im trying to be as detailed as possible because its not working or maybe Im just doing it wrong.

Now Im not trying to be ungrateful or out of pocket but every other HACS integration Ive added so far show up in the Add Integration, then ya key in your login info. Another approach is perhaps add the details for dummys or a picture (screenshot) showing how it should look via the manual part but like using 123@email.com / dummypass. This way ya eliminate room for error and dummy proof it.

**Comment by jfarmer08** [comment]
You should have changed the configuration.yaml and not the const.py file.

**Comment by tascotim** [comment]
Thanks. I'm new and I'm not sure of the formatting required for the above in the configuration file.

Tim
________________________________
